Setup event listeners
EvilCorpIncorporated/studylog pull request #9
Opened 2022-12-19 15:15 UTC by Galz648

2022-12-20 17:54 UTC, ohmree requested changes
There are some linter errors that should be easy to catch, plus some other code quality issues that I'd like to go over.

2022-12-21 10:44 UTC, ohmree commented on apps/web-extension/src/entries/background/constants/alarmNames.ts
> +export const alarmNames = {
First of all I don't think we should have an entire `constants` *directory* for constants.
Second of all, this code looks sketchy:
```ts
export const alarmNames = {
  heartbeatAlarm: 'heartbeatAlarm',
};
```
Typescript allows for more elegant ways to express this, namely literal types - meaning the string `'heartbeatAlarm'` can be its own type.
Or enums, although they typically aren't the ideal way to do just about anything in typescript.
> **Note**
> Do not *ever* use `const enum`s, they don't work with vite and are generally not a good feature.

2022-12-21 10:46 UTC, ohmree commented on apps/web-extension/package.json
> +    "mockzilla": "^0.14.0",
I don't know that we need `jest-localstorage-mock`.
What does it do for us?
We don't use `localStorage`, we use `browser.local.storage` for storing values locally (as one should when making a browser extension).

2022-12-21 11:07 UTC, ohmree commented on apps/web-extension/src/entries/background/activity.ts
> +    return tabs;
Assuming this mutative approach is the correct thing to do (is it?), it should be properly typed (it isn't ATM).

2022-12-21 11:10 UTC, ohmree commented on apps/web-extension/src/entries/background/tabs.ts
> +  new Error('Function not implemented.');
`new Error` on its own does nothing, this is definitely not the intended effect of this code and it should be rewritten to either throw the error or (preferably I think) use some other primitive error handling mechanism like `console.assert`.

2022-12-21 11:15 UTC, ohmree reviewed
Some of the issues I had with the current implementation could've easily been caught by using eslint and prettier with vscode and by having git hooks setup.
We should figure out how to include git hooks in a monorepo - since when files are changed in each workspace a different command needs to be executed.
For example - say `apps/web/foo.vue` is changed - we'd need to run `apps/web/node_modules/.bin/eslint --fix apps/web/foo.vue` (or the equivalent `pnpm` invocation in the right directory).

2022-12-21 11:21 UTC, ohmree reviewed
Some of the issues I had with the current implementation could've easily been caught by using eslint and prettier with vscode and by having git hooks setup.
We should figure out how to include git hooks in a monorepo - since when files are changed in each workspace a different command needs to be executed.
For example - say `apps/web/foo.vue` is changed - we'd need to run `apps/web/node_modules/.bin/eslint --fix apps/web/foo.vue` (or the equivalent `pnpm` invocation in the right directory).
This might require changing our eslint setup:
Currently we have each workspace depend on `eslint`, our shared rules that should apply to anything in the monorepo and additional workspace-specific rules, and each workspace's `.eslintrc` is set as the root config.
This is probably not ideal for performance (a new node process would have to be spawned for each workspace we lint) and it makes setting up `lint-staged` much less trivial.
Ideally I'd like to have `eslint` only be a top-level dependency, with per-workspace `.eslintrc`s not declaring themselves as `root: true`.

2022-12-21 11:24 UTC, ohmree commented
Oops - seems like you can't delete review comments and I have been adding new ones instead of editing the existing ones.
Please don't mind any comment but the latest one.

2022-12-29 18:47 UTC, Galz648 commented on apps/web-extension/src/entries/background/activity.ts
> +    return tabs;
this functionality has been changed in upcoming pull requests, and so this will be resolved when the branches are merged.
with this in mind, is still an issue ?

2022-12-29 18:49 UTC, Galz648 commented on apps/web-extension/src/entries/background/constants/alarmNames.ts
> +export const alarmNames = {
could you please give a code snippet detailing how your alternative will look like ? Thanks

2022-12-29 18:54 UTC, Galz648 commented on apps/web-extension/package.json
> +    "mockzilla": "^0.14.0",
https://github.com/EvilCorpIncorporated/studylog/pull/9/commits/03950a098b1fbb21f0b385b9c3491f1a34f6158b - fixed in this commit

2022-12-31 18:07 UTC, merged